### ISSUE TITLE
7 Steane error detection with QX-34-L

### ISSUE THREAD

**Issue by takkie-snoekie** [QuTech-Delft/qx-simulator#117]
We have written a code for the 7 Steane error detection in Quantum Inspire using the QX-34-L simulator (see picture for the circuit). We used the web version to run our code. When we don't implement any errors, we obtain the correct result when measuring the ancillas (all in the 0 state). When we apply an X-gate on qubit 0 from the data qubits to simulate a bit-flip error, you would expect that ancillas q10, q11, q12 are in the 1 state and ancillas q7, q8, q9 are in the 0 state (thus 111000 for the ancilla state). 
However, when running the simulation, we obtain four different states for the ancilla qubits (see histogram in picture). 
We have checked the code thoroughly, with slides from our lectures and with the book, but it all seems correct.

Our professor told us to report the error, because there might be a bug.

![circuit-X error on qubit 0](https://user-images.githubusercontent.com/122437948/211766711-27b89bf6-3ffe-498d-84c2-3861920a0977.png)
![image](https://user-images.githubusercontent.com/122437948/211767928-7b9d03bb-0119-4455-b690-0419719bd6e2.png)

**Comment by pablolh** [comment]
Hi [takkie-snoekie](https://github.com/takkie-snoekie)
Thanks for reporting the issue.
Can you please provide the cQasm circuit that you passed to the simulator?
There was a bug discovered recently that's already been fixed (but not yet in Quantum Inspire, that is the web version) and I'd like to see if they're the same/related.
Thanks!
