### ISSUE TITLE
Merge QX library with mainstream repository

### ISSUE THREAD

**Issue by lriesebos** [QuTech-Delft/qx-simulator#4]
For a while there exists a QX library repository with limited functionality. I have already been using this for a while for QUAPA, but there is more interest in integrating QX into other projects. Unfortunately there is mainly one problem we are facing: due to separate repositories the QX library does not benefit from features in the mainstream QX repository. The library lacks a lot of features which makes it less valuable.

Proposed solution:
Get to a single QX repository again which allows usage as standalone application as well as a static or dynamic library with a well defined interface. There are a few things which will be important to support on API level. These include but are not limited to:

1. Fine control over executed gates and circuits
1. Fine control over error model and elapsed time
1. Support for both stabilizer and universal backend in a transparent way (throwing exceptions in case an unsupported action is performed)
1. Control over number of threads/processes used for the QX simulation (all cores versus part of the cores versus one core)

**Comment by RichardVersluisTNO** [comment]
I think this issue should be closed. Outdated.
