### ISSUE TITLE
Set up output test

### ISSUE THREAD

**Issue by quantumkoen** [QuTech-Delft/qx-simulator#44]
Currently, we run tests to see if a variety of qasm files are parsed and executing without errors. We need to add checks of the output to make sure the simulator is behaving as expected after we refactor things to avoid having to manually test things (which inevitably will result in things overlooked and a risk of regressions creeping in).

**Comment by RichardVersluisTNO** [comment]
Not a useful and outdated ticket. Since we are picking up developments on QX again, unit testing should be included anyway.
Issue can be closed
