### ISSUE TITLE
Test-suite not running, 'make check' does nothing

### ISSUE THREAD

**Issue by quantumkoen** [QuTech-Delft/qx-simulator#5]
In the ```INSTALL``` file it says:

> Optionally, type `make check' to run any self-tests that come with the package, generally using the just-built uninstalled binaries.

Running ```make check``` gives me:

```
(env) kfjmartens@ubuntu-vm:~/src/EWI/qx-simulator/src$ make check
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/kfjmartens/src/EWI/qx-simulator/src/missing autoconf
(env) kfjmartens@ubuntu-vm:~/src/EWI/qx-simulator/src$
```
It does not look like any tests were executed.

**Comment by RichardVersluisTNO** [comment]
I think this issue can be closed
