### ISSUE TITLE
Number of classical bits and measurements should be independent of the number of qubits

### ISSUE THREAD

**Issue by quantumkoen** [QuTech-Delft/qx-simulator#63]
This was reported by Fer Grooteman to Quantum Inspire, but is an issue for qx-simulator, so i'm re-reporting here:

In QX sim the number of control bits equals the number of qubits. This is limiting the usage of QX as a simulator backend for, for example Qiskit, especially when conditional gates (binary controlled gates) are used.
Another limitation is the possibility to measure a qubit to a named classical bit. Now a q[x] is always measured in b[x]. 

In other quantum programming languages, e.g. OpenQASM, these topics are no limitation.
When the number of classical bits is higher than the number of qubits and measurements are done for binary controlled gates in classical bits we don't have, now we can't use QX as a simulator for these quantum programs.

For example the following (not very useful) Qiskit  example is not supported by our SDK:

```
    q = QuantumRegister(2)
    c = ClassicalRegister(3)
    qc = QuantumCircuit(q, c)

    qc.measure(q[0], c[0])
    qc.measure(q[0], c[1])
    qc.measure(q[0], c[2])
    qc.h(q[1]).c_if(c, 7)
    qc.measure(q[1], c[0])
```

The measurements of q[0] to c[1] and c[2] are not supported. In combination with using bit 2 in the condition for the binary controlled gate:
```
C-H b[0:2], q[1]
```

results in an QX-sim error:
`qx-simulator: /qx/src/qx-simulator/src/core/register.cc:371: bool qx::qu_register::test(uint64_t): Assertion `q<n_qubits' failed.\n`

It starts as a shortcoming in cQASM to be able to define this. Maybe we should make an extension on cQASM or  cQASM should evolve.

**Comment by pablolh** [comment]
Upcoming cQasm 3.0 and additional features in QX-simulator are planned to fixed this

**Comment by rturrado** [comment]
This is indeed not the case anymore. In cQASM 3.0, bits and qubits are treated independently.
