### ISSUE TITLE
Measurement outcome of multiple execution

### ISSUE THREAD

**Issue by prince-ph0en1x** [QuTech-Delft/qx-simulator#68]
The res variable is boolean type even if 100 tests are run.
How do I access the average value from the test code?

``` 
import qxelarator

qx = qxelarator.QX()
qx.set('rand.qasm')

NTests = 100
qx.execute(NTests)
res = qx.get_measurement_outcome(0)
```

The code above is the test_rand.py test case of Qxelerator

**Comment by pablolh** [comment]
get_measurement_outcome indeed shows the final value of the measurement register for that qubit.
You can easily compute an average per-qubit using the new output format (stdout or json)
