### ISSUE TITLE
Memory waste by 'qu_register::aux'

### ISSUE THREAD

**Issue by JinKiSung** [QuTech-Delft/qx-simulator#91]
The only caller of qu_register::aux is the qft class. Currently, since 'aux' space is always allocated to qu_register, there is a problem that 2^1 more memory is always consumed regardless of whether QFT is used or not.

To improve this, we propose to dynamically manage 'aux' space only when the qft class is called in the algorithm.

**Comment by pablolh** [comment]
That is very true. This aux member has nothing to do inside the register class, and can be created as a local variable in qft::apply

**Comment by pablolh** [comment]
I should fix this at some point within the next 2 weeks.
