### ISSUE TITLE
Change from git submodules to CMake FetchContent

### ISSUE THREAD

**Issue by mmoelle1** [QuTech-Delft/qx-simulator#94]
Dear QX developers,

did you consider changing from git submodules to the FetchContent mechanism (https://cmake.org/cmake/help/latest/module/FetchContent.html) that was introduced with CMake 3.11? Right now, the ZIP archive does not work because it does not include the `libqasm` dependency. If you want I can prepare a PR.

Kind regards,
Matthias

**Comment by pablolh** [comment]
Done
